modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
[[mods]]
modId="arcadia_pets"
version="1.0.0"
displayName="Arcadia Pets"
description="Collectible pet system with skills, fusion, HUD and collection."
[[dependencies.arcadia_pets]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.219,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcadia_pets]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcadia_pets]]
    modId="arcadia_lib"
    type="required"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
